### PR TITLE
Fix Zeus ultimate

### LINKED ISSUE #103: Zeus not using ultimate
I've never seen Zeus would use his ultimate. Lots of heroes did have the same problem, but I've played against Zeus yesterday 3 times so it's a hot topic  🗡️

### PR DESCRIPTION
**Pull request by JoshdanG**
1. Fixes various programming errors, especially:
- Avoiding the misbehaving Linq "Remove()" function
- Handling bots becoming "null" when we lose vision
2. Reorganized to track targets across interruptions (silence, stun, etc)
3. Lots of explanatory variables and comments added
4. Mostly follows original intended behavior

Fixes #103

### CODE REVIEW

File: ability_item_usage_zuus.lua [hunk 1]
```diff
@@ -19,9 +19,13 @@ end
 local Talents = {}
 local Abilities = {}
 local AbilitiesReal = {}
+npcBot.ult = {}
```
Comment (adamqqqplay) [inline ability_item_usage_zuus.lua:22]: Could you add some comments to that variable?

File: ability_item_usage_zuus.lua [hunk 2]
```diff
@@ -451,90 +457,132 @@ Consider[3] = function()
...
+			local enemyHero = enemyStats[3]
+			local wasKillable = enemyStats[4]
+			local isNull = ""
 
-	local ability = AbilitiesReal[6]
-	if not ability:IsFullyCastable()
-	then
-		return BOT_ACTION_DESIRE_NONE
-	end
+			if enemyBot:IsNull() then
```
Comment (adamqqqplay) [inline ability_item_usage_zuus.lua:473]: Is there a function IsNull() in Lua language? The general usage seems to be `enemyBot == nil`

**Review by adamqqqplay — COMMENTED** [review]
We really need to remove the misbehaving Linq "Remove()" function, I have seen many similar errors in the console before.

**Comment by JoshdanG** [comment]
> We really need to remove the misbehaving Linq "Remove()" function, I have seen many similar errors in the console before.

I'll submit a fix for it.  It probably won't fix much, because anything using it wasn't properly tested, but it will be one less bug.

File: ability_item_usage_zuus.lua (hunk 2 above)
Comment (JoshdanG) [reply ability_item_usage_zuus.lua:473]: I think IsNull() comes from the C interface.  Wherever it's from, it detects when a bot object _exists_ but is no longer valid.  From what I can see, when a bot goes out of vision, its object loses all of its API functions, _but is not nil_.  E.g. calling enemyBot:GetUnitName will return an error. This is only really an issue when keeping track of bots across frames.

I assume the reason it works this way is to prevent you from keeping track of the real hero by just tracking the object id.  Interestingly, it seems dying does not cause the object to be cleared.

File: ability_item_usage_zuus.lua (hunk 1 above)
Comment (JoshdanG) [reply ability_item_usage_zuus.lua]: done

File: ability_item_usage_zuus.lua (hunk 2 above)
Comment (adamqqqplay) [reply ability_item_usage_zuus.lua:473]: I get it, this is really interesting.

**Review by ArcherWayne — APPROVED** [review]
